### ISSUE TITLE
Tests are very slow. 

### ISSUE THREAD

**Issue by kbaikov** [simonw/datasette#1212]
Working on my PR i noticed that tests are very slow.

The plain pytest run took about 37 minutes for me.
However i could shave of about 10 minutes from that if i used pytest-xdist to parallelize execution.
`pytest -n 8` is run only in 28 minutes on my machine.

I can create a PR to mention that in your documentation.
This will be a simple change to add pytest-xdist to requirements and change a command to run pytest in documentation.

Does that make sense to you?

After a bit more investigation it looks like python-xdist is not an answer. It creates a race condition for tests that try to clead temp dir before run.

Profiling shows that most time is spent on conn.executescript(TABLES) in make_app_client function. Which makes sense.

Perhaps the better approach would be look at the app_client fixture which is already session scoped, but not used by all test cases.
And/or use conn = sqlite3.connect(":memory:") which is much faster.
And/or truncate tables after each TC instead of deleting the file and re-creating them.

I can take a look which is the best approach if you give the go-ahead.

**Comment by simonw** [comment]
37 minutes, wow! They're a little slow for me (4-5 minutes perhaps) but not nearly that bad.

Thanks for running that profile. I think you're right: figuring out how to use more session scopes would definitely help.

The `:memory:` idea is interesting too. The new `memory_name=` feature added in #1151 (released in Datasette 0.54) could help a lot here, since it allows Datasette instances to share the same in-memory database across multiple HTTP requests and connections.

Note that `memory_name=` also persists within test runs themselves, independently of any `scope=` options on the fixtures. That might actually help us here!

I'd be delighted if you explored this issue further, especially the option of using `memory_name=` for the fixtures databases used by the tests.

**Comment by simonw** [comment]
It would be great if we could get `python-xdist` to run too - I tried it in the past and gave up when I ran into those race conditions, but I've not done any further digging to see if there's a way to fix that.

**Comment by kbaikov** [comment]
How do you get 4-5 minutes?
I run my tests in WSL 2, so may be i need to try a real linux VM.

**Comment by kbaikov** [comment]
I will close this issue since it appears only in my particular setup.
