### ISSUE TITLE
`--get '/:memory:.json?sql=select+3*5'` error with datasette 0.59

### ISSUE THREAD

**Issue by chenrui333** [simonw/datasette#1493]
👋  trying to upgrade the formula to use the latest release, but runs into some regression test issue with `--get` command.

My QQ is does this `datasette --get '/:memory:.json?sql=select+3*5'` supposed to return 15? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/87369

**Comment by simonw** [comment]
I renamed `/:memory:` to `/_memory` in version 0.55 - https://docs.datasette.io/en/stable/changelog.html#v0-55

But... in 0.59 I stopped following HTTP redirects by default, which is why this used to work and no longer does!

So the fix is to update the Homebrew regression test to use this instead:

    datasette --get '/_memory.json?sql=select+3*5'

Thanks for catching this!
