### ISSUE TITLE
Custom pages don't work on windows

### ISSUE THREAD

**Issue by stroll** [simonw/datasette#1545]
It seems that custom pages don't work when put in templates/pages

To reproduce on datasette version 0.59.4  using PowerShell on WIndows 10 with Python 3.10.0

    mkdir -p templates/pages

    echo "hello world" >> templates/pages/about.html

Start datasette
   
    datasette --template-dir templates/

Navigate to [http://127.0.0.1:8001/about](url) and receive:
    
   Error 404:
   Database not found: about

**Comment by simonw** [comment]
Here's the relevant code: https://github.com/simonw/datasette/blob/4094741c2881c2ada3f3f878b532fdaec7914953/datasette/app.py#L1204-L1219

It's using `route_path.split("/")` which should be OK because that's the incoming `request.path` path - which I would expect to use `/` even on Windows. Then it uses `os.path.join` which should do the right thing.

I need to get myself a proper Windows development environment setup to investigate this one.

**Comment by simonw** [comment]
I understand the problem now! https://github.com/pallets/jinja/issues/1378#issuecomment-812410922

> Jinja template names/paths are not always filesystem paths. So regardless of the OS Jinja always uses forward slashes.

**Comment by simonw** [comment]
Filed an issue with Jinja suggesting a documentation update:
- https://github.com/pallets/jinja/issues/1578
