### ISSUE TITLE
add hash id to "_memory" url if hashed url mode is turned on and crossdb is also turned on

### ISSUE THREAD

**Issue by fgregg** [simonw/datasette#1561]
If hashed_url mode is turned on and crossdb is also turned on, then queries to _memory should have a hash_id. 

One way that it could work is to have the _memory hash be a hash of all the individual databases.

Otherwise, crossdb queries can get quit out of data if using aggressive caching.

**Comment by simonw** [comment]
Oh that's an interesting solution, combining the hashes of all of the individual databases.

I'm actually not a big fan of `hashed_url` mode - I implemented it right at the start of the project because it felt like a clever hack, and then ended up making it not-the-default a few years ago:

- #418
- #419
- #421

I've since not found myself wanting to use it at all for any of my projects - which makes me nervous, because it means there's a pretty complex feature that I'm not using at all, so it's only really protected by the existing unit tests for it.

What I'd really like to do is figure out how to have hashed URL mode work entirely as a plugin - then I could extract it from Datasette core entirely (which would simplify a bunch of stuff) but people who find the optimization useful would be able to access it.

I'm not sure that the existing plugin hooks are robust enough to do that yet though.

**Comment by fgregg** [comment]
interesting! i love this feature. this + full caching with cloudflare is really super!

**Comment by simonw** [comment]
I ended up moving hashed URL mode out to a plugin in:
- #647

If you're still interested in using it with `_memory` please open an issue in that repo here: https://github.com/simonw/datasette-hashed-urls
