### ISSUE TITLE
Move canned queries closer to the SQL input area

### ISSUE THREAD

**Issue by jsfenfen** [simonw/datasette#1612]
*Original title:  Consider placing example queries above the sql input?*

Hi! Have been enjoying deploying ad hoc datasettes for collaborators to pick over! 

I keep finding myself manually "fixing" the database.html template so that the "example queries" (canned queries) appear directly *over* the sql box? So they are sorta more a suggestion for collaborators who aren't inclined to write their own queries? 

My sense is any time I go to the trouble of writing canned queries my users should see 'em? 

(( I have also considered a client-side reactive-ish option where selecting a query just places the raw SQL in the box and doesn't execute it, but this seems to end up being an inconvenience, rather than a teaching tool. ))

**Comment by simonw** [comment]
That's a much better place for them, I like this idea.

**Comment by simonw** [comment]
They're currently shown at the very bottom of the page, under the list of tables and far away from the SQL query box: https://latest.datasette.io/fixtures

<img width="353" alt="image" src="https://user-images.githubusercontent.com/9599/151034640-c3b79214-7fec-4137-b3ed-45541167feff.png">

I'm also questioning if "Queries" is the best header for this. Other options:

- Canned queries (what the feature is called in the documentation, but I don't think it's a great user-facing term)
- Sample or Example queries - I don't like these much because they're more than just examples - they are often the core functionality of the specific customized Datasette instance
- Prepared queries - overlaps with terminology used in other databases, so not great either
- Pre-configured queries - urgh, don't like that language, feels clumsy
- Query recipes - bit out of left-field this one, only really makes sense for queries that include named parameters for specific use-cases

Maybe "Queries" is right after all.

**Comment by simonw** [comment]
Here's something I like: I also added a "Tables" `<h2>` heading and bumped the tables themselves down from a `<h2>` to a `<h3>`:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/9599/151035671-9920db99-a943-46a6-8cd8-7a0ad7524474.png">

**Comment by simonw** [comment]
OK, that's live on https://latest.datasette.io/fixtures now - I really like it. Thanks for the suggestion!

**Comment by jsfenfen** [comment]
OMG, this might be the fastest OS ticket I've ever filed, thanks so much @simonw
