### ISSUE TITLE
Preserve query on timeout

### ISSUE THREAD

**Issue by danp** [simonw/datasette#1819]
If a query hits the timeout it shows a message like:

> SQL query took too long. The time limit is controlled by the [sql_time_limit_ms](https://docs.datasette.io/en/stable/settings.html#sql-time-limit-ms) configuration option.

But the query is lost. Hitting the browser back button shows the query _before_ the one that errored.

It would be nice if the query that errored was preserved for more tweaking. This would make it similar to how "invalid syntax" works since #1346 / #619.

**Comment by simonw** [comment]
This is a good idea.

**Comment by simonw** [comment]
Implementing it like this, so at least you can copy and paste the SQL query back out again:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/9599/192395953-48512c94-10e0-4cf8-8ae5-b9e65e3d7b0f.png">

I'm not doing a full textarea because this error can be raised in multiple places, including on the table page itself. It's not just an error associated with the manual query page.

**Comment by simonw** [comment]
Demo: https://latest.datasette.io/_memory?sql=with+recursive+counter(x)+as+(%0D%0A++select+0%0D%0A++++union%0D%0A++select+x+%2B+1+from+counter%0D%0A)%2C%0D%0Ablah+as+(select+*+from+counter+limit+5000000)%0D%0Aselect+count(*)+from+blah
