### ISSUE TITLE
Datasette 1.0 Canned Queries Broken

### ISSUE THREAD

**Issue by brandonrobertz** [simonw/datasette#2364]
Canned queries in metadata.yml don't seem to work in datasette `1.0a13`. I've tested in `0.64.8` and it works fine. Here's my metadata file (`metadata.yml`):

```
databases:
  db_name:
    queries:
      my_canned_query:
        sql: |-
          select 1
```

In `0.64.8` this works as expected. In `1.0a13` this causes every page to explode with the following error:

```
Error binding parameter 3: type 'dict' is not supported
Traceback (most recent call last):
  File "/Users/brandon/src/datasette/datasette/app.py", line 1726, in route_path
    response = await view(request, send)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/app.py", line 1893, in async_view_for_class
    return await async_call_with_supported_arguments(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/utils/__init__.py", line 1022, in async_call_with_supported_arguments
    return await fn(*call_with)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/views/base.py", line 89, in __call__
    return await handler(request, datasette)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/views/database.py", line 44, in get
    await datasette.refresh_schemas()
  File "/Users/brandon/src/datasette/datasette/app.py", line 504, in refresh_schemas
    await self._refresh_schemas()
  File "/Users/brandon/src/datasette/datasette/app.py", line 510, in _refresh_schemas
    await self.apply_metadata_json()
  File "/Users/brandon/src/datasette/datasette/app.py", line 459, in apply_metadata_json
    await self.set_database_metadata(dbname, key, value)
  File "/Users/brandon/src/datasette/datasette/app.py", line 749, in set_database_metadata
    await self.get_internal_database().execute_write(
  File "/Users/brandon/src/datasette/datasette/database.py", line 129, in execute_write
    results = await self.execute_write_fn(_inner, block=block)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/database.py", line 191, in execute_write_fn
    return await self._send_to_write_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/database.py", line 216, in _send_to_write_thread
    raise result
  File "/Users/brandon/src/datasette/datasette/database.py", line 256, in _execute_writes
    result = task.fn(conn)
             ^^^^^^^^^^^^^
  File "/Users/brandon/src/datasette/datasette/database.py", line 126, in _inner
    return conn.execute(sql, params or [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Error binding parameter 3: type 'dict' is not supported
```

A bisect suggests the explosions problem began with e1bfab3fca22e4f8d06dcf419e945f13fc20aef1 . Likely the issue began earlier with 35deaabcb105903790d18710a26e77545f6852ce when canned queries simply disappeared from the UI silently.

Did the format for canned queries change with the metadata refactors? The documentation still lists the original metadata format, but perhaps that's not actually what's expected anymore?

**Comment by asg017** [comment]
Hey @brandonrobertz ! Sorry for the delay, I didn't see this issue before

This has to do with many breaking changes we're adding to `v1`, including how we handle metadata and "configuration"

The tl;dr: Use the new [`datasette.yaml`](https://docs.datasette.io/en/latest/configuration.html#canned-queries-configuration) file to store canned queries, and `metadata.yaml` strictly for database/table metadata.  This change is described in #2093 


The long answer: for a while we've been worried about how `metadata.yaml` has become a kitchen sink of all Datasette configuration, when it was originally meant for just metadata (ex title/descriptions of tables and databases, about URLs, licensing, etc.). So we came up with [`datasette.yaml`](https://docs.datasette.io/en/latest/configuration.html#datasette-yaml-reference) to move all non-metadata related configuration to a separate file. 

Which means canned queries now need to be in that new file. It's a very similar structure so copy+pasting your `metadata.yaml` into `datasette.yaml` and removing metadata-related keys should work as expected, but let us know if the transition is difficult. 

Most importantly: this is documeted on the [latest version of docs.datasette.io](https://docs.datasette.io/en/latest), but the [stable version](https://docs.datasette.io/en/stable/) still points to `0.64.x`, which doesn't include any of this `datasette.yaml` stuff, since that's strictly in `1.0a` builds. Maybe we can create a specific 1.0 page to document this for people who want to try bleeding edge stuff. 

Again sorry for the delay, and apologies for the configuration confusion!

**Comment by brandonrobertz** [comment]
Thank you so much for the explanation. This makes a lot more sense now. Closing!

**Comment by simonw** [comment]
You can also upgrade metadata to the new config format with this plugin: https://github.com/datasette/datasette-upgrade

```bash
datasette upgrade metadata-to-config metadata.json -m metadata.yml -c datasette.yml
```
