### ISSUE TITLE
Datasette doesn't reload when database file changes

### ISSUE THREAD

**Issue by psychemedia** [simonw/datasette#431]
My understanding of the `--reload` option was that if the database file changed `datasette` would automatically reload.

I'm running on a Mac and from the `datasette` UI queries don't seem to be picking up data in a newly changed db (I checked the db timestamp - it certainly updated).

I was also expecting to see some sort of log statement in the datasette logging to say that it had detected a file change and restarted, but don't see anything there?

Will try to check on an Ubuntu box when I get a chance to see if this is a Mac thing.

**Comment by simonw** [comment]
You should be able to see the reload happening in the console logs:

<img width="1045" alt="tmp_—_sqlite3_fixtures_db_—_80×25_and_tmp_—_Python_◂_datasette_--reload_fixtures_db_-p_8052_—_154×57_and_datasette_—_python3_7__usr_local_Cellar_pipenv_2018_11_26_libexec_bin_pipenv_shell_▸_bash_—_147×43" src="https://user-images.githubusercontent.com/9599/56084524-d347ba80-5de8-11e9-9fc8-6e902244a92a.png">

I'm doing some work at the moment to handle mutating files MUCH better - #419 - my goal is to have Datasette work against SQLite files that are being updated out-of-the box, and change the current immutable behaviour to be an option rather than the default.

**Comment by psychemedia** [comment]
Hmm... nope... I see an updated timestamp from `ls -al`  on the db but no reload?

**Comment by simonw** [comment]
Datasette master now treats databases as readonly but NOT immutable. This means you can make changes to those databases from another process and those changes will be instantly reflected in the Datasette interface.

As such, reloading on database change is no longer necessary. Closing this ticket.
