### ISSUE TITLE
Exporting sqlite database(s)?

### ISSUE THREAD

**Issue by chrismp** [simonw/datasette#502]
I'm working on datasette from one computer. But if I want to work on it from another computer and want to copy the SQLite database(s) already on the Heroku datasette instance, how to I copy the database(s) to the second computer so that I can then update it and push to online via datasette's command line code that pushes code to Heroku?

**Comment by simonw** [comment]
There should be a "Download SQLite DB" link at the bottom of each database page - e.g. on https://latest.datasette.io/fixtures 

<img width="815" alt="fixtures" src="https://user-images.githubusercontent.com/9599/59298300-1bdff080-8c3f-11e9-8d75-b3eb6e1ae385.png">

Does that solve this? Re-open the issue if it doesn't!

**Comment by chrismp** [comment]
Hm, neither that text nor that link appear on the site

**Comment by chrismp** [comment]
It appears that I cannot reopen this issue but the proposed solution did not solve it.

**Comment by louispotok** [comment]
For what it's worth, if anyone finds this in the future, I was having the same issue. 

After digging through the code, it turned out that the database download is only available if it the db served in immutable mode, so `datasette serve -i xyz.db` rather than the doc's quickstart recommendation of `datasette serve xyz.db`.
