### ISSUE TITLE
?_searchmode=raw option for running FTS searches without escaping characters

### ISSUE THREAD

**Issue by tunguyenatwork** [simonw/datasette#676]
After the version 0.34.  I am not able to use the wildchar in the _search option( or the full text search). It will not return any result unless I specify the whole word for text search.  

If I use 'match :search || "*" ' in the sql statement then it will work as expected.

**Comment by simonw** [comment]
I'm afraid this is by design: supporting wildcards in that mode was more-or-less accidental and often resulted in unexpected user-facing syntax errors when users accidentally entered search text that included characters with special meaning to SQLite.

You can still execute wildcard searches but you have to do so using custom SQL statements.

I'm open to suggestions for more friendly ways to support this functionality. Would an alternative `_search_wildcard=` URL parameter be worth supporting I wonder? What's your specific use-case for wildcards?

**Comment by tunguyenatwork** [comment]
Thanks Simon,
My use case is using Datasette for full text search type ahead.  That was working pretty well. The _search_wildcard= option will be awesome.  Thanks

**Comment by simonw** [comment]
I'm going to call it `?_search_raw=` because it will pass through the value as a raw (unprocessed) argument to SQLite FTS, which means it will expose features other than just wildcards: https://www.sqlite.org/fts5.html#full_text_query_syntax

**Comment by simonw** [comment]
`?_search_raw=` doesn't work because it clashes with an existing feature - you can use `?_search_colname=` to search just within a specific column, and there could possibly be a column called `raw`.

I could go with `?_searchraw=` - or maybe have an additional "mode" selection like `?_search=foo*&_searchmode=raw`

**Comment by simonw** [comment]
Nice thing about the "mode" concept is that I can optionally reflect it in the HTML UI in some way - maybe with a checkbox for "raw" mode that only shows up if the user hits the page with `?_searchmode=raw` in the querystring.

**Comment by simonw** [comment]
You can try this right now like so:

    pip install https://github.com/simonw/datasette/archive/search-raw.zip

Then use the following:

    ?_search=foo*&_searchmode=raw`

**Comment by simonw** [comment]
Still needs documentation before I can land it in master.

**Comment by tunguyenatwork** [comment]
Awesome, thank you so much. I’ll try it out and let you know.

**Comment by simonw** [comment]
OK, this is in master now. You can install master using:

    pip install https://github.com/simonw/datasette/archive/master.zip

Documentation here: https://datasette.readthedocs.io/en/latest/json_api.html#special-table-arguments
