### ISSUE TITLE
Question: Any fixed date for the release with the uft8-encoding fix?

### ISSUE THREAD

**Issue by clausjuhl** [simonw/datasette#757]
Just a little impatient :)

**Comment by simonw** [comment]
I'll definitely get that out this week!

For the moment a trick I often use is to put a URL to the most recent commit in my `requirements.txt` - e.g. https://github.com/simonw/datasette/archive/0784f2ef9d3ff6dd9df05f54cb51de29a6d11764.zip

This should be safe because nothing lands on Datasette master without the full unit test suite passing. But you're right, there's a bunch of stuff now that needs to go out in a release: https://github.com/simonw/datasette/compare/0.40...0784f2ef9d3ff6dd9df05f54cb51de29a6d11764

**Comment by simonw** [comment]
Actually I'm going to put that release out today. I was hoping to finish #698 first but that shouldn't delay those other features any longer.

**Comment by simonw** [comment]
OK, I just released 0.41 with that and a bunch of other stuff: https://datasette.readthedocs.io/en/latest/changelog.html#v0-41
