### ISSUE TITLE
Allow to specify a URL fragment for canned queries

### ISSUE THREAD

**Issue by rixx** [simonw/datasette#767]
Canned queries are very useful to direct users to prepared data and views. I like to use them with charts using datasette-vega a lot, because people get a direct impression at first glance.

datasette-vega doesn't show up by default though, and users have to click through to it. Also, datasette-vega does not always guess the best way to render columns correctly though, so it would be nice if I could specify a URL fragment in my canned queries to make sure people see what I want them to see.

My current workaround is to include a fragement link in ``description_html`` and ask people to reload the page, like [here](https://data.rixx.de/songs/show_by_bpm#g.mark=bar&g.x_column=bpm_floor&g.x_type=ordinal&g.y_column=bpm_count&g.y_type=quantitative), which is a bit hacky.

**Comment by simonw** [comment]
Interesting. So this would take effect exclusively on pages that link to the queries, which I think just means this page: https://latest.datasette.io/fixtures

How about this for the design: there's a new optional key in the metadata configuration for a query called `"fragment"` - used like this:

```json
{
    "databases": {
        "fixtures": {
            "queries": {
                "neighborhood_search": {
                    "sql": "\nselect neighborhood, facet_cities.name, state\nfrom facetable\n    join facet_cities\n        on facetable.city_id = facet_cities.id\nwhere neighborhood like '%' || :text || '%'\norder by neighborhood;\n",
                    "title": "Search neighborhoods",
                    "description_html": "<b>Demonstrating</b> simple like search",
                    "name": "neighborhood_search",
                    "fragment": "sql-format"
                }
            }
        }
    }
}
```
Because of the `"fragment": "sql-format"` bit there the link to that query from https://latest.datasette.io/fixtures would be to `https://latest.datasette.io/fixtures/neighborhood_search#sql-format`.

Does that cover what you need here? Have I missed anything?

**Comment by rixx** [comment]
That would be perfect!
