### ISSUE TITLE
How to setup a request limit per user

### ISSUE THREAD

**Issue by Krazybug** [simonw/datasette#899]
Hello,

Until now I'm using  datasette without any authentication system but I would like to setup a configuration  or limiting the number of requests per user (eventually by IP or with a cookie mechanism) and eventually allowing me to ban specific users/IPs.

Is there a plugin available for this use case ? 
If not what are your insights regarding this UC ?

Should I write a plugin ? Should I deploy datasette behind a reverse proxy to manage this ?

**Comment by simonw** [comment]
There's no mechanism that can do this at the moment.

You could absolutely support this with a plugin, probably using the `asgi_wrapper` plugin hook. There's an existing package at https://pypi.org/project/asgi-ratelimit/ which may be usable for this - it may even be possible to configure that using https://github.com/simonw/datasette-configure-asgi rather than using it to write a custom plugin.

Using a separate revers proxy would also be a good way to solve this. It depends which option would work best in your environment.
